import { isJapaneseMatch } from './util';

export const japanese_country_names = {
    Afghanistan: ['アフガニスタン'],
    Angola: ['アンゴラ'],
    Albania: ['アルバニア'],
    'United Arab Emirates': ['アラブ首長国連邦', 'UAE'],
    Argentina: ['アルゼンチン'],
    Armenia: ['アルメニア'],
    'French Southern Territories': ['フランス領南方・南極地域'],
    Australia: ['オーストラリア'],
    Austria: ['オーストリア'],
    Azerbaijan: ['アゼルバイジャン'],
    Burundi: ['ブルンジ'],
    Belgium: ['ベルギー'],
    Benin: ['ベナン'],
    'Burkina Faso': ['ブルキナファソ'],
    Bangladesh: ['バングラデシュ'],
    Bulgaria: ['ブルガリア'],
    Bahamas: ['バハマ'],
    'Bosnia and Herzegovina': ['ボスニア・ヘルツェゴビナ'],
    Belarus: ['ベラルーシ'],
    Belize: ['ベリーズ'],
    Bolivia: ['ボリビア'],
    Brazil: ['ブラジル'],
    Brunei: ['ブルネイ'],
    Bhutan: ['ブータン'],
    Botswana: ['ボツワナ'],
    'Central African Republic': ['中央アフリカ'],
    Canada: ['カナダ'],
    Switzerland: ['スイス'],
    Chile: ['チリ'],
    China: ['中国'],
    "Cote d'Ivoire": ['コートジボワール'],
    Cameroon: ['カメルーン'],
    'Democratic Republic of Congo': ['コンゴ民主共和国'],
    Congo: ['コンゴ共和国'],
    Colombia: ['コロンビア'],
    'Costa Rica': ['コスタリカ'],
    Cuba: ['キューバ'],
    Cyprus: ['キプロス'],
    Czechia: ['チェコ'],
    Germany: ['ドイツ'],
    Djibouti: ['ジブチ'],
    Denmark: ['デンマーク'],
    Greenland: ['グリーンランド'],
    'Dominican Republic': ['ドミニカ共和国'],
    Algeria: ['アルジェリア'],
    Ecuador: ['エクアドル'],
    Egypt: ['エジプト'],
    Eritrea: ['エリトリア'],
    Spain: ['スペイン'],
    Estonia: ['エストニア'],
    Ethiopia: ['エチオピア'],
    Finland: ['フィンランド'],
    Fiji: ['フィジー'],
    France: ['フランス'],
    'French Guiana': ['フランス領ギアナ'],
    Gabon: ['ガボン'],
    'United Kingdom': ['イギリス'],
    Georgia: ['ジョージア', 'グルジア'],
    Ghana: ['ガーナ'],
    Guinea: ['ギニア'],
    Gambia: ['ガンビア'],
    'Guinea-Bissau': ['ギニアビサウ'],
    'Equatorial Guinea': ['赤道ギニア'],
    Greece: ['ギリシャ'],
    Guatemala: ['グアテマラ'],
    Guyana: ['ガイアナ'],
    Honduras: ['ホンジュラス'],
    Croatia: ['クロアチア'],
    Haiti: ['ハイチ'],
    Hungary: ['ハンガリー'],
    Indonesia: ['インドネシア'],
    India: ['インド'],
    Ireland: ['アイルランド'],
    Iran: ['イラン'],
    Iraq: ['イラク'],
    Iceland: ['アイスランド'],
    Israel: ['イスラエル'],
    Italy: ['イタリア'],
    Jamaica: ['ジャマイカ'],
    Jordan: ['ヨルダン'],
    Japan: ['日本'],
    Kazakhstan: ['カザフスタン'],
    Kenya: ['ケニア'],
    Kyrgyzstan: ['キルギス'],
    Cambodia: ['カンボジア'],
    'South Korea': ['韓国', '大韓民国'],
    Kosovo: ['コソボ'],
    Kuwait: ['クウェート'],
    Laos: ['ラオス'],
    Lebanon: ['レバノン'],
    Liberia: ['リベリア'],
    Libya: ['リビア'],
    'Sri Lanka': ['スリランカ'],
    Lesotho: ['レソト'],
    Lithuania: ['リトアニア'],
    Luxembourg: ['ルクセンブルク'],
    Latvia: ['ラトビア'],
    Morocco: ['モロッコ'],
    Moldova: ['モルドバ'],
    Madagascar: ['マダガスカル'],
    Mexico: ['メキシコ'],
    'North Macedonia': ['北マケドニア'],
    Mali: ['マリ'],
    Myanmar: ['ミャンマー'],
    Montenegro: ['モンテネグロ'],
    Mongolia: ['モンゴル'],
    Mozambique: ['モザンビーク'],
    Mauritania: ['モーリタニア'],
    Malawi: ['マラウイ'],
    Malaysia: ['マレーシア'],
    Namibia: ['ナミビア'],
    'New Caledonia': ['ニューカレドニア'],
    Niger: ['ニジェール'],
    Nigeria: ['ナイジェリア'],
    Nicaragua: ['ニカラグア'],
    Netherlands: ['オランダ'],
    Norway: ['ノルウェー'],
    Nepal: ['ネパール'],
    'New Zealand': ['ニュージーランド'],
    Oman: ['オマーン'],
    Pakistan: ['パキスタン'],
    Panama: ['パナマ'],
    Peru: ['ペルー'],
    Philippines: ['フィリピン'],
    'Papua New Guinea': ['パプアニューギニア'],
    Poland: ['ポーランド'],
    'Puerto Rico': ['プエルトリコ'],
    'North Korea': ['北朝鮮'],
    Portugal: ['ポルトガル'],
    Paraguay: ['パラグアイ'],
    Qatar: ['カタール'],
    Romania: ['ルーマニア'],
    Russia: ['ロシア'],
    Rwanda: ['ルワンダ'],
    'Western Sahara': ['西サハラ'],
    'Saudi Arabia': ['サウジアラビア'],
    Sudan: ['スーダン'],
    'South Sudan': ['南スーダン'],
    Senegal: ['セネガル'],
    'Solomon Islands': ['ソロモン諸島'],
    'Sierra Leone': ['シエラレオネ'],
    'El Salvador': ['エルサルバドル'],
    Somalia: ['ソマリア'],
    Serbia: ['セルビア'],
    Suriname: ['スリナム'],
    Slovakia: ['スロバキア'],
    Slovenia: ['スロベニア'],
    Sweden: ['スウェーデン'],
    Eswatini: ['エスワティニ'],
    Syria: ['シリア'],
    Chad: ['チャド'],
    Togo: ['トーゴ'],
    Thailand: ['タイ'],
    Tajikistan: ['タジキスタン'],
    Turkmenistan: ['トルクメニスタン'],
    Timor: ['東ティモール'],
    'Trinidad and Tobago': ['トリニダード・トバゴ', 'トリニダードトバゴ'],
    Tunisia: ['チュニジア'],
    Turkey: ['トルコ'],
    Taiwan: ['台湾'],
    Tanzania: ['タンザニア'],
    Uganda: ['ウガンダ'],
    Ukraine: ['ウクライナ'],
    Uruguay: ['ウルグアイ'],
    'United States': ['アメリカ合衆国', 'アメリカ'],
    Uzbekistan: ['ウズベキスタン'],
    Venezuela: ['ベネズエラ'],
    Vietnam: ['ベトナム'],
    Vanuatu: ['バヌアツ'],
    'West Bank': ['ヨルダン川西岸地区', 'ヨルダン川西岸'],
    Yemen: ['イエメン'],
    'South Africa': ['南アフリカ'],
    Zambia: ['ザンビア'],
    Zimbabwe: ['ジンバブエ'],
    'Cape Verde': ['カーボベル'],
    Comoros: ['コモロ'],
    Mauritius: ['モーリシャス'],
    Seychelles: ['セーシェル'],
    Bahrain: ['バーレーン'],
    Maldives: ['モルディブ'],
    'Marshall Islands': ['マーシャル', 'マーシャル諸島'],
    'Micronesia (country)': ['ミクロネシア連邦'],
    Nauru: ['ナウル'],
    Palau: ['パラオ'],
    Samoa: ['サモア'],
    Singapore: ['シンガポール'],
    Tonga: ['トンガ'],
    Tuvalu: ['ツバル'],
    'Antigua and Barbuda': [
        'アンティグア・バーブーダ',
        'アンティグアバーブーダ',
        'アンティガ・バーブーダ',
        'アンティガバーブーダ',
    ],
    Barbados: ['バルバドス'],
    Dominica: ['ドミニカ国'],
    Grenada: ['グレナダ'],
    'Saint Kitts and Nevis': ['セントクリストファー・ネイビス', 'セントクリストファーネイビス'],
    'Saint Lucia': ['セントルシア'],
    'Saint Vincent and the Grenadines': [
        'セントビンセント・グレナディーン',
        'セントビンセントグレナディーン',
    ],
    Andorra: ['アンドラ'],
    Liechtenstein: ['リヒテンシュタイン'],
    Malta: ['マルタ'],
    Monaco: ['モナコ'],
    'San Marino': ['サンマリノ'],
    Kiribati: ['キリバス'],
    'Sao Tome and Principe': ['サントメ・プリンシペ', 'サントメプリンシペ'],
};

export const getJpNames = (name: keyof typeof japanese_country_names | string) => {
    return japanese_country_names[name as keyof typeof japanese_country_names] || name;
};

//日本語の国名を英語に変換する関数
export const translateCountryNameToEnglish = (
    name: keyof typeof japanese_country_names | string,
) => {
    const english_country_names = Object.fromEntries(
        Object.entries(japanese_country_names).map(([key, value]) => [value, key]),
    );
    return english_country_names[name as keyof typeof english_country_names] || name;
};

export const checkAnswer = (inputStr: string, answer: string) => {
    const jpNames = getJpNames(answer);
    let isMatch = false;
    for (const name of jpNames) {
        if (isJapaneseMatch(inputStr, name)) {
            isMatch = true;
            break;
        }
    }
    return isMatch;
};
