export const countryRegion = {
    Afghanistan: 'アジア',
    Angola: 'アフリカ',
    Albania: 'ヨーロッパ',
    'United Arab Emirates': 'アジア',
    Argentina: '南アメリカ',
    Armenia: 'アジア',
    'French Southern Territories': '南極',
    Australia: 'オーストラリア',
    Austria: 'ヨーロッパ',
    Azerbaijan: 'アジア',
    Burundi: 'アフリカ',
    Belgium: 'ヨーロッパ',
    Benin: 'アフリカ',
    'Burkina Faso': 'アフリカ',
    Bangladesh: 'アジア',
    Bulgaria: 'ヨーロッパ',
    Bahamas: '北アメリカ',
    'Bosnia and Herzegovina': 'ヨーロッパ',
    Belarus: 'ヨーロッパ',
    Belize: '北アメリカ',
    Bolivia: '南アメリカ',
    Brazil: '南アメリカ',
    Brunei: 'アジア',
    Bhutan: 'アジア',
    Botswana: 'アフリカ',
    'Central African Republic': 'アフリカ',
    Canada: '北アメリカ',
    Switzerland: 'ヨーロッパ',
    Chile: '南アメリカ',
    China: 'アジア',
    "Cote d'Ivoire": 'アフリカ',
    Cameroon: 'アフリカ',
    'Democratic Republic of Congo': 'アフリカ',
    Congo: 'アフリカ',
    Colombia: '南アメリカ',
    'Costa Rica': '北アメリカ',
    Cuba: '北アメリカ',
    Cyprus: 'アジア',
    Czechia: 'ヨーロッパ',
    Germany: 'ヨーロッパ',
    Djibouti: 'アフリカ',
    Denmark: 'ヨーロッパ',
    Greenland: '北アメリカ',
    'Dominican Republic': '北アメリカ',
    Algeria: 'アフリカ',
    Ecuador: '南アメリカ',
    Egypt: 'アフリカ',
    Eritrea: 'アフリカ',
    Spain: 'ヨーロッパ',
    Estonia: 'ヨーロッパ',
    Ethiopia: 'アフリカ',
    Finland: 'ヨーロッパ',
    Fiji: 'オーストラリア',
    France: 'ヨーロッパ',
    'French Guiana': '南アメリカ',
    Gabon: 'アフリカ',
    'United Kingdom': 'ヨーロッパ',
    Georgia: 'アジア',
    Ghana: 'アフリカ',
    Guinea: 'アフリカ',
    Gambia: 'アフリカ',
    'Guinea-Bissau': 'アフリカ',
    'Equatorial Guinea': 'アフリカ',
    Greece: 'ヨーロッパ',
    Guatemala: '北アメリカ',
    Guyana: '南アメリカ',
    Honduras: '北アメリカ',
    Croatia: 'ヨーロッパ',
    Haiti: '北アメリカ',
    Hungary: 'ヨーロッパ',
    Indonesia: 'アジア',
    India: 'アジア',
    Ireland: 'ヨーロッパ',
    Iran: 'アジア',
    Iraq: 'アジア',
    Iceland: 'ヨーロッパ',
    Israel: 'アジア',
    Italy: 'ヨーロッパ',
    Jamaica: '北アメリカ',
    Jordan: 'アジア',
    Japan: 'アジア',
    Kazakhstan: 'アジア',
    Kenya: 'アフリカ',
    Kyrgyzstan: 'アジア',
    Cambodia: 'アジア',
    'South Korea': 'アジア',
    Kosovo: 'ヨーロッパ',
    Kuwait: 'アジア',
    Laos: 'アジア',
    Lebanon: 'アジア',
    Liberia: 'アフリカ',
    Libya: 'アフリカ',
    'Sri Lanka': 'アジア',
    Lesotho: 'アフリカ',
    Lithuania: 'ヨーロッパ',
    Luxembourg: 'ヨーロッパ',
    Latvia: 'ヨーロッパ',
    Morocco: 'アフリカ',
    Moldova: 'ヨーロッパ',
    Madagascar: 'アフリカ',
    Mexico: '北アメリカ',
    'North Macedonia': 'ヨーロッパ',
    Mali: 'アフリカ',
    Myanmar: 'アジア',
    Montenegro: 'ヨーロッパ',
    Mongolia: 'アジア',
    Mozambique: 'アフリカ',
    Mauritania: 'アフリカ',
    Malawi: 'アフリカ',
    Malaysia: 'アジア',
    Namibia: 'アフリカ',
    'New Caledonia': 'オーストラリア',
    Niger: 'アフリカ',
    Nigeria: 'アフリカ',
    Nicaragua: '北アメリカ',
    Netherlands: 'ヨーロッパ',
    Norway: 'ヨーロッパ',
    Nepal: 'アジア',
    'New Zealand': 'オーストラリア',
    Oman: 'アジア',
    Pakistan: 'アジア',
    Panama: '北アメリカ',
    Peru: '南アメリカ',
    Philippines: 'アジア',
    'Papua New Guinea': 'オーストラリア',
    Poland: 'ヨーロッパ',
    'Puerto Rico': '北アメリカ',
    'North Korea': 'アジア',
    Portugal: 'ヨーロッパ',
    Paraguay: '南アメリカ',
    Qatar: 'アジア',
    Romania: 'ヨーロッパ',
    Russia: 'ヨーロッパ',
    Rwanda: 'アフリカ',
    'Western Sahara': 'アフリカ',
    'Saudi Arabia': 'アジア',
    Sudan: 'アフリカ',
    'South Sudan': 'アフリカ',
    Senegal: 'アフリカ',
    'Solomon Islands': 'オーストラリア',
    'Sierra Leone': 'アフリカ',
    'El Salvador': '北アメリカ',
    Somalia: 'アフリカ',
    Serbia: 'ヨーロッパ',
    Suriname: '南アメリカ',
    Slovakia: 'ヨーロッパ',
    Slovenia: 'ヨーロッパ',
    Sweden: 'ヨーロッパ',
    Eswatini: 'アフリカ',
    Syria: 'アジア',
    Chad: 'アフリカ',
    Togo: 'アフリカ',
    Thailand: 'アジア',
    Tajikistan: 'アジア',
    Turkmenistan: 'アジア',
    Timor: 'アジア',
    'Trinidad and Tobago': '北アメリカ',
    Tunisia: 'アフリカ',
    Turkey: 'アジア',
    Taiwan: 'アジア',
    Tanzania: 'アフリカ',
    Uganda: 'アフリカ',
    Ukraine: 'ヨーロッパ',
    Uruguay: '南アメリカ',
    'United States': '北アメリカ',
    Uzbekistan: 'アジア',
    Venezuela: '南アメリカ',
    Vietnam: 'アジア',
    Vanuatu: 'オーストラリア',
    'West Bank': 'アジア',
    Yemen: 'アジア',
    'South Africa': 'アフリカ',
    Zambia: 'アフリカ',
    Zimbabwe: 'アフリカ',
    'Cape Verde': 'アフリカ',
    Comoros: 'アフリカ',
    Mauritius: 'アフリカ',
    Seychelles: 'アフリカ',
    Bahrain: 'アジア',
    Maldives: 'アジア',
    'Marshall Islands': 'オーストラリア',
    'Micronesia (country)': 'オーストラリア',
    Nauru: 'オーストラリア',
    Palau: 'オーストラリア',
    Samoa: 'オーストラリア',
    Singapore: 'アジア',
    Tonga: 'オーストラリア',
    Tuvalu: 'オーストラリア',
    'Antigua and Barbuda': '北アメリカ',
    Barbados: '北アメリカ',
    Dominica: '北アメリカ',
    Grenada: '北アメリカ',
    'Saint Kitts and Nevis': '北アメリカ',
    'Saint Lucia': '北アメリカ',
    'Saint Vincent and the Grenadines': '北アメリカ',
    Andorra: 'ヨーロッパ',
    Liechtenstein: 'ヨーロッパ',
    Malta: 'ヨーロッパ',
    Monaco: 'ヨーロッパ',
    'San Marino': 'ヨーロッパ',
    Kiribati: 'オーストラリア',
    'Sao Tome and Principe': 'アフリカ',
};

export const getRegion = (countryName: string) => {
    return countryRegion[countryName as keyof typeof countryRegion] || null;
};
